plugins:
  - jemoji

markdown: GFM

page_excerpts: true
show_excerpts: true

author:
  name: Kevin Wyckmans
  email: kevinwyckmans@gmail.com
  github: kwyckmans
  twitter: kwyckmans

  sass:
    sass_dir: _sass