# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
# gem "jekyll"
gem "github-pages", "~> 228"
# gem "minima", :github => 'jekyll/minima'
