# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "github-pages", "~> 228"
gem "jekyll-remote-theme"
gem 'jekyll-feed'

# Currently I can't run jekyll locally without uncommenting this. 
#  and if I leave it, github pages fails to build.
#  Need to downgrade my local ruby version to make this work (I think).
gem "webrick", "~> 1.8"
